version: "2"

services:
  zookeeper:
    image: jplock/zookeeper
  marathon:
    image: mesosphere/marathon
    command:
      --master local --zk zk://zookeeper:2181/marathon
    links:
      - zookeeper
    ports:
      - "8080"